Add tests
jgfofgTA/MyBlog pull request #23
Opened 2022-09-19 14:25 UTC by jgfofgTA

2022-10-06 15:02 UTC, MaximStadnikov requested changes

2022-10-06 15:02 UTC, MaximStadnikov commented on spec/models/comment_spec.rb
> +      expect { comment.save }.to change(Comment, :count).by(1)
здесь та же ситуация, что и в предыдущем файле

2022-10-06 15:02 UTC, MaximStadnikov commented on spec/models/user_spec.rb
> +      expect { user.save }.to change(described_class, :count).by(1)
и тут

2022-10-06 15:02 UTC, MaximStadnikov commented on spec/models/user_spec.rb
> +describe User, type: :model do
Почему ты в этом файле описываешь тест вот так, а, к примеру, в файле `models/comments_spec.rb` вот так: `describe 'Comment', type: :model do`? В чем разница?

2022-10-06 15:05 UTC, jgfofgTA commented on spec/features/articles/article_spec.rb
> +      expect(page).to have_current_path "/articles/#{Article.last.id}", ignore_query: true
Это тоже рубокоп

2022-10-06 15:17 UTC, jgfofgTA commented on spec/features/articles/article_spec.rb
> +class ArticleClass
Нельзя создавать константы вне класса вроде бы

2022-10-06 15:18 UTC, jgfofgTA commented on spec/features/articles/article_spec.rb
> +      expect(page).to have_current_path '/articles'
При ошибке создания статьи происходит редирект на /articles. Я до этого написал /articles/new, но это выдавало ошибку

2022-10-06 15:27 UTC, jgfofgTA commented on spec/models/user_spec.rb
> +describe User, type: :model do
Не заметил почему-то

2022-10-07 14:27 UTC, MaximStadnikov commented
@jgfofgTA не забудь пожалуйста поменять все константы на переменные, объявленные через let. Это только в тестах, если что)

2022-10-29 10:49 UTC, MaximStadnikov approved these changes

2022-11-14 10:47 UTC, merged