Add test
jgfofgTA/MyBlog pull request #6
Opened 2022-08-01 12:31 UTC by jgfofgTA

2022-08-04 11:55 UTC, sergeyantonov1 commented on spec/features/user_spec.rb
> +RSpec.describe "User registration" do
`Rspec.describe` используется для описания класса либо для описания метода. Подробнее можно прочитать здесь: https://www.betterspecs.org/#describe

Сама структура теста должна выглядить примерно как в этой документации: https://relishapp.com/rspec/rspec-rails/v/5-0/docs/feature-specs/feature-spec
```ruby
require "rails_helper"

RSpec.feature "User registration" do
  scenario "User signs up" do
    visit new_user_registration_path
    fill_in 'Email', with: "user@example.com"
    fill_in 'Password', with: "password"
    fill_in 'Password confirmation', with: "password"
    fill_in 'First name', with: "password"
    fill_in 'Last name', with: "password"
    click_button 'Sign up'
    expect(page).to have_content 'Здравствуйте'
  end
end
```

2022-08-04 11:55 UTC, sergeyantonov1 commented on spec/features/user_spec.rb
> +RSpec.describe "User registration" do
Также регистрация пользователя и логин пользователя - это две разных фичи, поэтому их стоит отделить на разные файлы

2022-08-08 10:42 UTC, ArthurZaharov requested changes

2022-08-08 10:42 UTC, ArthurZaharov commented on spec/features/user_spec.rb
> +RSpec.describe "User registration" do
@jgfofgTA а что с этими комментами? Надо разделить на два файла signup & singin.

2022-08-08 10:42 UTC, ArthurZaharov commented on spec/models/article_spec.rb
> +    let(:article_params) { { title: "article title", body: "lorem ipsum", status: "public", user: user } }
FactoryBot тут надо использовать в каждом контексте
```ruby
let(:user) { build :user }
```

2022-08-08 10:42 UTC, ArthurZaharov commented on test/models/article_test.rb
>  require 'test_helper'
Этот файл можно совсем удалить, он для minitest

2022-08-08 12:04 UTC, ArthurZaharov commented on Gemfile
> +gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
А просто  `gem 'faker'` не работает? Зачем указывать master ветку тут?

2022-08-08 12:04 UTC, ArthurZaharov commented on spec/features/user_sign_in.rb
> +Rspec.describe "#user" do
RSpec можно убрать в тестах
```
describe ... do
  feature ... do
  end
end
```

2022-08-08 12:04 UTC, ArthurZaharov commented on spec/models/article_spec.rb
> +    let(:article_params) { { title: "article title", body: "lorem ipsum", status: "public", user: user } }
Вот посмотри как тут сделано - https://github.com/DominaPluviam/my_project/pull/6/files#diff-d319a8fedb48067418a804668bdd086508689cb5ec51d54525788f418c32c705R1

2022-08-08 13:36 UTC, ArthurZaharov approved these changes

2022-08-09 07:37 UTC, merged