Add ci cd
jgfofgTA/MyBlog pull request #8
Opened 2022-08-04 08:00 UTC by jgfofgTA

2022-08-09 12:58 UTC, ArthurZaharov requested changes

2022-08-09 12:58 UTC, ArthurZaharov commented on bin/test
> +bin/rspec spec/models
```suggestion
bin/rspec spec
```

2022-08-09 12:58 UTC, ArthurZaharov commented on bin/quality
> +rubocop
Все через binstubs
bin/...

2022-08-09 12:58 UTC, ArthurZaharov commented on bin/quality
> +bundle-audit
Надо еще update делать перед проверкой
bin/bundle-audit update

2022-08-09 12:58 UTC, ArthurZaharov commented on .github/workflows/learn-github-actions.yml
> +name: learn-github-actions
Это часть другого ПР

2022-08-09 12:58 UTC, ArthurZaharov commented on .gitignore
> +.DS_Store
Уже закомиченные файлы убрать надо

2022-08-09 12:59 UTC, ArthurZaharov requested changes

2022-08-09 12:59 UTC, ArthurZaharov commented on bin/quality
> +rubocop
В начале надо добавлять
```
#!/usr/bin/env ruby
```
хоть ruby тут и не используется

2022-08-09 14:18 UTC, ArthurZaharov commented on bin/quality
> +`bin/bundle-audit update`
`bin/bundle-audit check`

в конце должно быть

2022-08-09 14:30 UTC, jgfofgTA commented on bin/test
> +`bin/rspec spec/features/user_sign_in.rb`
Оставил, потому что в консоли при запуске bin/rspec spec работал только тест в модели
Или они тоже работали но в консоли не отображались?

2022-08-10 09:44 UTC, ArthurZaharov requested changes

2022-08-10 09:44 UTC, ArthurZaharov commented on app/models/user.rb
> +  has_many :articles, dependent: nil
Такой опции для dependent нет (https://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_many)

2022-08-10 09:44 UTC, ArthurZaharov commented on bin/quality
> +`bin/rubocop -A`
Мы вчера смотрели и так не очень работает. Лучше вот так
```ruby
#!/usr/bin/env sh

bin/slim-lint app/views/
bin/scss-lint app/assets/stylesheets/
bin/brakeman
bin/bundle-audit update
bin/bundle-audit check
```

2022-08-10 09:44 UTC, ArthurZaharov commented on bin/test
> +#!/usr/bin/env ruby
и тут тоже

2022-08-10 10:14 UTC, ArthurZaharov approved these changes

2022-08-10 10:17 UTC, merged